//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojDziennikv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Event_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<int> Duration_In_Days { get; set; }
        public string Describe { get; set; }
        public string Account_Group { get; set; }
        public override string ToString()
        {
            return "Event Id: " + Event_Id + " Employee Id: " +
                Employee_Id.GetValueOrDefault() + " Start Time: " + Start_Time.GetValueOrDefault().ToShortDateString() +
                " Duration in days: " + Duration_In_Days.GetValueOrDefault() + " Describe: " + Describe +
                " Account group: " + Account_Group;
        }
        public virtual Employee Employee { get; set; }
    }
}
