//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojDziennikv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int Lesson_Id { get; set; }
        public string Class_Number { get; set; }
        public int Subject_Id { get; set; }
        public int Employee_Id { get; set; }
        public int Day_Of_Week { get; set; }
        public string Start_Time { get; set; }
        public string Class_Room_Number { get; set; }
    
        public virtual Class_Room Class_Room { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual School_Class School_Class { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
