//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojDziennikv4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MojDziennikEntities : DbContext
    {
        public MojDziennikEntities()
            : base("name=MojDziennikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Class_Room> Class_Room { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Legal_Guardian> Legal_Guardian { get; set; }
        public virtual DbSet<Lesson> Lesson { get; set; }
        public virtual DbSet<Mark> Mark { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<Pupil> Pupil { get; set; }
        public virtual DbSet<School_Class> School_Class { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<Event> Event { get; set; }
    }
}
