//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojDziennikv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Note_Id { get; set; }
        public int Pupil_Id { get; set; }
        public int Employee_Id { get; set; }
        public System.DateTime Note_Date { get; set; }
        public bool Positve { get; set; }
        public string Describe { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Pupil Pupil { get; set; }
    }
}
