//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MojDziennikv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupil : IPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pupil()
        {
            this.Mark = new HashSet<Mark>();
            this.Note = new HashSet<Note>();
        }
    
        public int Pupil_Id { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Surname { get; set; }
        public string Pesel_Number { get; set; }
        public int Legal_Guardian_Id { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string School_Id_Card_Number { get; set; }
        public int Account_Id { get; set; }
        public string Class_Number { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Legal_Guardian Legal_Guardian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark> Mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Note { get; set; }
        public virtual School_Class School_Class { get; set; }
    }
}
